sudo: required
services:
  - docker

before_install:
  - docker build -t kkaralaitis/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kkaralaitis/react-test npm test -- --coverage

after-success:
  - docker build -t kkaralaitis/multi-client ./client
  - docker build -t kkaralaitis/multi-nignx ./nginx
  - docker build -t kkaralaitis/multi-server ./server
  - docker build -t kkaralaitis/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kkaralaitis/multi-client
  - docker push kkaralaitis/multi-nignx
  - docker push kkaralaitis/multi-server
  - docker push kkaralaitis/multi-worker